### ISSUE TITLE
What do you need?

### ISSUE THREAD

**Issue by MemeHoovy** [Joalor64GH/hxDVD#1]
you invited me to the repo, what do you need?

**Comment by Joalor64GH** [comment]
just some help cause this is one of my first haxelib extensions

**Comment by MemeHoovy** [comment]
ah, okay, so your trying to make a DVD player in haxe?

**Comment by MemeHoovy** [comment]
that may or may not be possible due to how limited haxe is

**Comment by MemeHoovy** [comment]
albeit it allows C++ or C# though

**Comment by Joalor64GH** [comment]
got it

**Comment by MemeHoovy** [comment]
https://github.com/HaxeFoundation/haxe/issues/10818

**Comment by polybiusproxy** [comment]
Got invited too. A Haxe library for reading DVDs seems a bit unnecessary, but it's possible.

**Comment by MemeHoovy** [comment]
Hi poly!
