### ISSUE TITLE
how do i add this on friday night funkin?

### ISSUE THREAD

**Issue by JonnycatMeow** [Joalor64GH/hxDVD#2]
how do i play video on it? please add a wiki

**Comment by MemeHoovy** [comment]
it's not finished yet

**Comment by JonnycatMeow** [comment]
oh ok and also one more question will it also play .mp4 video?

**Comment by JonnycatMeow** [comment]
or just dvd's only

**Comment by MemeHoovy** [comment]
Idk, I haven't worked that out yet
